"""Red-first proof: generator refuses an unmerged index instead of corrupting.

Pins the bug in issue #74: `tools/generate_source_declaration.py` derived its
path list from `git ls-files -- '*.py'`, which emits a conflicted path once
per merge stage. That produced a `python_paths` list with duplicates, which
`tools/admission_root_v1.py::parse_declaration` rejects at import time -- and
`--check` compared the corrupt output against itself, so it reported
"PASS source declaration is current" on the broken state.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DECLARATION_RELATIVE_PATH = Path(".github/admission/v1/source-declaration.json")
CONFLICT_PATH = "aec/mentor.py"


class UnmergedIndexGeneratorTests(unittest.TestCase):
    """Prove the generator and its --check both refuse an unmerged index."""

    def _cloned_root(self) -> Path:
        clone = Path(self.enterContext(tempfile.TemporaryDirectory())) / "clone"
        subprocess.run(
            ["git", "clone", "--quiet", "--local", str(ROOT), str(clone)],
            check=True,
        )
        return clone

    def _make_index_unmerged(self, root: Path, path: str) -> None:
        """Stage `path` at conflict stages 1/2/3, as a real unresolved merge does.

        Git requires the existing stage-0 entry to be removed (mode 0, null
        SHA) before conflict stages can be inserted -- without that removal
        record the stage-0 entry lingers alongside stages 1/2/3, which is a
        mixed state `git status`/`git diff` never produce from a real merge.
        """
        blob = subprocess.run(
            ["git", "hash-object", "-w", str(root / path)],
            cwd=root,
            check=True,
            capture_output=True,
        ).stdout.decode().strip()
        removal = f"0 {'0' * 40}\t{path}\n"
        index_info = removal + "".join(
            f"100644 {blob} {stage}\t{path}\n" for stage in (1, 2, 3)
        )
        subprocess.run(
            ["git", "update-index", "--index-info"],
            cwd=root,
            input=index_info.encode("utf-8"),
            check=True,
        )

    def test_unmerged_index_is_refused_by_both_generate_and_check(self) -> None:
        """Pins both halves of #74 in one repo state: writing and --check.

        Runs the generator script *from the clone* (not GENERATOR / the real
        checkout's copy): the script derives its own ROOT from `__file__`, so
        invoking the real checkout's script would silently inspect the real
        checkout's git state instead of the clone's unmerged index, regardless
        of the `cwd=` passed to subprocess.run.
        """
        root = self._cloned_root()
        cloned_generator = root / "tools" / "generate_source_declaration.py"
        declaration_path = root / DECLARATION_RELATIVE_PATH
        original = declaration_path.read_bytes()
        self._make_index_unmerged(root, CONFLICT_PATH)

        generate_result = subprocess.run(
            [sys.executable, str(cloned_generator)],
            cwd=root,
            capture_output=True,
            text=True,
        )
        check_result = subprocess.run(
            [sys.executable, str(cloned_generator), "--check"],
            cwd=root,
            capture_output=True,
            text=True,
        )

        self.assertNotEqual(0, generate_result.returncode)
        self.assertIn("unmerged", generate_result.stdout.lower())
        self.assertEqual(
            original,
            declaration_path.read_bytes(),
            "generator must not overwrite the declaration while the index is unmerged",
        )
        self.assertNotEqual(0, check_result.returncode)
        self.assertNotIn("PASS", check_result.stdout)

    def test_check_rejects_a_declaration_that_fails_to_parse(self) -> None:
        """`--check` must fail via `parse_declaration`, not just byte comparison.

        The unmerged-index guard returns before either byte comparison or
        `parse_declaration` runs, so the test above can't exercise this path:
        if `admission_root_v1.parse_declaration` never actually validated the
        declaration, this test -- unlike a purely byte-comparison test -- would
        catch it (see the mutation-verify note below).

        This test keeps the index clean and corrupts a field
        `build_declaration` carries forward unchanged (`schema_version`), so
        the regenerated bytes match the corrupted committed bytes exactly
        (same `python_paths`/`sources`, so a pure byte comparison would find
        nothing wrong and print PASS) and only real contract validation can
        catch the defect.

        `tools/admission_root_v1.py` self-validates its own committed
        declaration at import time (`BASE_DECLARATION = load_declaration(...)`,
        reading the very same file `--check` reads), so a corrupt on-disk
        declaration makes `generate_source_declaration.py` fail during
        `from tools.admission_root_v1 import parse_declaration` itself --
        before argument parsing, before the unmerged-index guard, before
        `main()` runs at all. That failure is a traceback rooted in
        `admission_root_v1.py`'s `parse_declaration`, not the "FAIL source
        declaration is stale" byte-comparison message `--check` prints on a
        merely-stale file, so it still proves the corruption is caught via
        real contract validation and not via string inequality.

        Mutation-verify (performed manually, not asserted here): with the
        `schema_version != DECLARATION_SCHEMA_VERSION` check in
        `admission_root_v1.parse_declaration` commented out, this exact
        corruption is no longer rejected -- the clone imports fine and
        `--check` prints PASS, exit 0. That confirms this test's failure
        genuinely depends on `parse_declaration` performing real validation,
        not on the JSON simply being malformed.
        """
        root = self._cloned_root()
        cloned_generator = root / "tools" / "generate_source_declaration.py"
        declaration_path = root / DECLARATION_RELATIVE_PATH

        payload = json.loads(declaration_path.read_text(encoding="utf-8"))
        payload["schema_version"] = "9.9.9"
        corrupted = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        declaration_path.write_text(corrupted, encoding="utf-8")
        subprocess.run(
            ["git", "add", str(DECLARATION_RELATIVE_PATH)],
            cwd=root,
            check=True,
            capture_output=True,
        )

        self.assertEqual([], self._unmerged_paths(root), "fixture must start with a clean index")

        check_result = subprocess.run(
            [sys.executable, str(cloned_generator), "--check"],
            cwd=root,
            capture_output=True,
            text=True,
        )

        self.assertNotEqual(0, check_result.returncode)
        self.assertNotIn("PASS", check_result.stdout)
        self.assertNotIn(
            "stale",
            check_result.stdout.lower(),
            "must not be caught merely as a byte-inequality/staleness mismatch",
        )
        self.assertIn(
            "admission_root_v1.py",
            check_result.stderr,
            "failure must be attributable to admission_root_v1's parse_declaration",
        )
        self.assertIn("parse_declaration", check_result.stderr)
        self.assertIn("schema_version is unsupported", check_result.stderr)

    def _unmerged_paths(self, root: Path) -> list[str]:
        output = subprocess.run(
            ["git", "ls-files", "-z", "--unmerged"],
            cwd=root,
            check=True,
            capture_output=True,
        ).stdout
        return [entry for entry in output.decode("utf-8").split("\0") if entry]


if __name__ == "__main__":
    unittest.main()
